### PR TITLE
Feature/pricing updates

### PR DESCRIPTION
**Pull request by probablyrory**
added byo pricing option

### CODE REVIEW

**Comment by chexton** [comment]
I made significant changes to this branch:

- Changed layout of "self-hosted" option.
- Added a full list of features based on a feature request list sent to me by Cloudflare (things they were looking for).
- Add an extra pricing tier for clarity.
- Change some of the headings and general wording.
- Add some emoji /shrug.

The styles are now a bit FUBAR, so going to leave that to @probablyrory – I didn't touch the styles branch on `vero-styles` at all :).

**Comment by probablyrory** [comment]
@chexton made some style changes.

**Comment by chexton** [comment]
Slick, I reckon nearly ready.

I observed this, is it me? I did re-pull styles but I reckon you didn't push up some tweaks you made on the styles repo.

screen shot 2017-01-31 at 10 30 49 pm

**Comment by chexton** [comment]
:shipit:

**Pull request merged**
